// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.28;

import {BasePaymaster} from "@account-abstraction/contracts/core/BasePaymaster.sol";
import {IEntryPoint} from "@account-abstraction/contracts/interfaces/IEntryPoint.sol";
import {PackedUserOperation} from "@account-abstraction/contracts/interfaces/PackedUserOperation.sol";
import {BaseAccount} from "@account-abstraction/contracts/core/BaseAccount.sol";
import {MembershipNFT} from "./MembershipNFT.sol";

/// @title ClubPaymaster - sponsors exactly one kind of UserOperation: an approved account calling MembershipNFT.join()
/// @notice Glue code generated by Blockchain Lab Forge on top of eth-infinitism BasePaymaster (Blockchains fork).
contract ClubPaymaster is BasePaymaster {
    MembershipNFT public immutable club;
    uint256 public maxCostPerOp;

    constructor(IEntryPoint ep, MembershipNFT club_, uint256 maxCost, address owner_) BasePaymaster(ep, owner_) {
        club = club_;
        maxCostPerOp = maxCost;
    }

    function setMaxCost(uint256 maxCost) external onlyOwner { maxCostPerOp = maxCost; }

    function _validatePaymasterUserOp(PackedUserOperation calldata op, bytes32, uint256 maxCost)
        internal view override returns (bytes memory context, uint256 validationData)
    {
        if (maxCost > maxCostPerOp || !club.approved(op.sender) || club.memberToken(op.sender) != 0) return ("", 1);
        bytes memory expected = abi.encodeCall(BaseAccount.execute, (address(club), 0, abi.encodeCall(MembershipNFT.join, ())));
        if (keccak256(op.callData) != keccak256(expected)) return ("", 1);
        return ("", 0);
    }
}
