// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {ERC721} from "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import {ERC721URIStorage} from "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import {AccessControl} from "@openzeppelin/contracts/access/AccessControl.sol";

/// @title MembershipNFT - one soul-bound-by-default membership pass per approved account
/// @notice Glue code generated by Blockchain Lab Forge. ERC721 + ERC721URIStorage + AccessControl from OpenZeppelin (Blockchains fork).
contract MembershipNFT is ERC721URIStorage, AccessControl {
    bytes32 public constant ADMIN_ROLE = DEFAULT_ADMIN_ROLE;
    bytes32 public constant APPROVER_ROLE = keccak256("APPROVER_ROLE");

    mapping(address => bool) public approved;
    mapping(address => uint256) public memberToken;
    uint256 public nextId = 1;
    string public baseMetadataURI;
    bool public transferable;

    event Approved(address indexed account, bool allowed);
    event Joined(address indexed member, uint256 indexed tokenId);

    error NotApproved(address account);
    error AlreadyMember(address account);
    error NonTransferable();

    constructor(address admin, string memory baseURI_) ERC721("Blockchain Lab Club", "BLCLUB") {
        _grantRole(ADMIN_ROLE, admin);
        _grantRole(APPROVER_ROLE, admin);
        baseMetadataURI = baseURI_;
    }

    function setApproved(address account, bool allowed) external onlyRole(APPROVER_ROLE) {
        approved[account] = allowed;
        emit Approved(account, allowed);
    }

    function setTransferable(bool on) external onlyRole(ADMIN_ROLE) {
        transferable = on;
    }

    /// @notice Called by an approved account (typically an ERC-4337 smart account) to mint its pass.
    function join() external returns (uint256 id) {
        if (!approved[msg.sender]) revert NotApproved(msg.sender);
        if (memberToken[msg.sender] != 0) revert AlreadyMember(msg.sender);
        id = nextId++;
        memberToken[msg.sender] = id;
        _safeMint(msg.sender, id);
        _setTokenURI(id, string.concat(baseMetadataURI, _toString(id), ".json"));
        emit Joined(msg.sender, id);
    }

    function isMember(address account) external view returns (bool) {
        return memberToken[account] != 0 && _ownerOf(memberToken[account]) == account;
    }

    function _update(address to, uint256 tokenId, address auth) internal override returns (address from) {
        from = _ownerOf(tokenId);
        if (from != address(0) && to != address(0) && !transferable) revert NonTransferable();
        return super._update(to, tokenId, auth);
    }

    function supportsInterface(bytes4 id) public view override(ERC721URIStorage, AccessControl) returns (bool) {
        return super.supportsInterface(id);
    }

    function _toString(uint256 v) private pure returns (string memory s) {
        if (v == 0) return "0";
        uint256 len;
        for (uint256 t = v; t != 0; t /= 10) len++;
        bytes memory b = new bytes(len);
        while (v != 0) { b[--len] = bytes1(uint8(48 + v % 10)); v /= 10; }
        return string(b);
    }
}
